version: "3"
services:
  web:
    build: ../apache
    env_file:
      - ../.env
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./app:/app
      - ../apache/exemplo.lan.conf:/etc/apache2/sites-enabled/exemplo.lan.conf
      - ../apache/certificados:/certificados

  db:
    image: mysql:8.3
    ports:
      - 3306:3306
    env_file:
      - ./.env_basedatos
    volumes:
      - ./bd/backup:/docker-entrypoint-initdb.d
      - datos:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  datos:
